version: 2.1

jobs:
  test:
    machine:
      image: windows-default
    steps:
      - checkout

      # Install Node.js using Chocolatey
      - run:
          name: Install Node.js
          command: |
            choco install nodejs-lts -y
            refreshenv

      # Install project dependencies
      - run:
          name: Install Dependencies
          command: npm install

      # Install Playwright browsers
      - run:
          name: Install Playwright Browsers
          command: npx playwright install

      # Run Playwright tests
      - run:
          name: Run Playwright Tests
          command: npx playwright test --headless

workflows:
  version: 2
  test_and_deploy:
    jobs:
      - test

