version: 2.1

executors:
  linux_executor:
    docker:
      - image: circleci/node:16-browsers

jobs:
  test:
    executor: linux_executor
    steps:
      - checkout

      # Install dependencies
      - run:
          name: Install Dependencies
          command: npm install

      # Install Playwright browsers (if necessary)
      - run:
          name: Install Playwright Browsers
          command: npx playwright install

      # Run Playwright tests in headless mode (you can use --headed if you need to see the browser)
      - run:
          name: Run Playwright Tests
          command: npx playwright test --headless

workflows:
  version: 2
  test_and_deploy:
    jobs:
      - test
